# Inserts a blank line between shell prompts
add_newline = false
right_format = """$time"""

[directory]
style = "red"

[line_break]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[time]
format = "[$time]($style)"
disabled = false
use_12hr = true
style = "red"

[cmd_duration]
disabled = true
