web_server:
  #  bind: 127.0.0.1
  port: 8443
  ssl_certificate: "/etc/flexget/bruh.pem"
  ssl_private_key: "/etc/flexget/haha.key"
  web_ui: yes

variables: yes

tasks:
  Anime:
    rss: https://subsplease.org/rss/?r=1080
    series:
      #      - X:
      #          set:
      #            path: "{? seasonaldir ?}X"

      #      - Tate no Yuusha no Nariagari Season 2:
      #          set:
      #            path: "{? seasonaldir ?}Tate no Yuusha no Nariagari Season 2"

      #      - Kaguya-sama wa Kokurasetai -Ultra Romantic-:
      #          set:
      #            path: "{? seasonaldir ?}Kaguya-sama wa Kokurasetai -Ultra Romantic-"

      #      - Spy x Family:
      #          set:
      #            path: "{? seasonaldir ?}Spy x Family"

      #      - Date A Live IV:
      #          set:
      #            path: "{? seasonaldir ?}Date A Live IV"

      #      - Shijou Saikyou no Daimaou, Murabito A ni Tensei suru:
      #          set:
      #            path: "{? seasonaldir ?}Shijou Saikyou no Daimaou, Murabito A ni Tensei suru"

      #      - Kawaii dake ja Nai Shikimori-san:
      #          set:
      #            path: "{? seasonaldir ?}Kawaii dake ja Nai Shikimori-san"

      #      - Yuusha, Yamemasu:
      #          set:
      #            path: "{? seasonaldir ?}Yuusha, Yamemasu"

      #      - Kakkou no Iinazuke:
      #          set:
      #            path: "{? seasonaldir ?}Kakkou no Iinazuke"

      #      - Otome Game Sekai wa Mob ni Kibishii Sekai desu:
      #          set:
      #            path: "{? seasonaldir ?}Otome Game Sekai wa Mob ni Kibishii Sekai desu"

      #      - Aharen-san wa Hakarenai:
      #          set:
      #            path: "{? seasonaldir ?}Aharen-san wa Hakarenai"

      #      - Koi wa Sekai Seifuku no Ato de:
      #          set:
      #            path: "{? seasonaldir ?}Koi wa Sekai Seifuku no Ato de"

      - Arifureta Shokugyou de Sekai Saikyou S2:
          set:
            path: "{? seasonaldir ?}Arifureta Shokugyou de Sekai Saikyou/S02"

      - Sabikui Bisco:
          set:
            path: "{? seasonaldir ?}Sabikui Bisco"

      - Tensai Ouji no Akaji Kokka Saisei Jutsu:
          set:
            path: "{? seasonaldir ?}Tensai Ouji no Akaji Kokka Saisei Jutsu"

      - Shikkakumon no Saikyou Kenja:
          set:
            path: "{? seasonaldir ?}Shikkakumon no Saikyou Kenja"

      - Sono Bisque Doll wa Koi wo Suru:
          set:
            path: "{? seasonaldir ?}Sono Bisque Doll wa Koi wo Suru"

      - Genjitsu Shugi Yuusha no Oukoku Saikenki:
          set:
            path: "{? seasonaldir ?}Genjitsu Shugi Yuusha no Oukoku Saikenki"

      - Princess Connect! Re-Dive S2:
          set:
            path: "{? seasonaldir ?}Princess Connect! Re-Dive S2"

    transmission:
      host: localhost
      port: 42069
      username: "{? trans.user ?}"
      password: "'{? trans.pw ?}'"

schedules:
  - tasks: Anime
    schedule:
      hour: 0-2
      minute: "*/8"
  - tasks: Anime
    schedule:
      hour: 4
  - tasks: Anime
    schedule:
      hour: 21-23
      minute: "*/8"
