name: Build

on:
  push:
    paths:
      - "linux.bash"
      - "server.bash"
      - "mac.bash"
      - "!sh"
      - "!mac"
  workflow_dispatch:

jobs:
  buildl:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install shc
        run: |
          sudo apt install -y shc
      - name: Pre-Cleanup
        run: |
          rm flag
          rm sh
          rm server
      - name: Build
        run: |
          shc -rvf linux.bash -o sh
          shc -rvf server.bash -o server
      - name: Post-Cleanup
        run: |
          rm linux.bash.x.c
          rm server.bash.x.c
      - name: increment version
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          TAGY="${TAG:5:2}
          TAGX=$(($TAGY+1))
          TAGA="${TAG:0:5}"
          TAGF="$TAGA$TAGX"
      - name: set up git
        run: |
          gpg --import "${{ secrets.SUPERKEY }}"
          git config --global user.signingkey 6372B76B1D9482B2
          git config --global commit.gpgsign true
          git config --local user.email "joshua@joseos.com"
          git config --local user.name "joshybot 🤖"
      - name: Commit
        run: |
          git add .
          git commit -m "🤖"
          git tag "$TAGF"
          git push origin "$TAGF"
          git push origin main
  buildm:
    name: Build for MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install shc
        run: |
          brew install shc
      - name: Pre-Cleanup
        run: |
          rm mac
      - name: Build
        run: |
          shc -rvf mac.bash -o mac
      - name: Post-Cleanup
        run: |
          rm mac.bash.x.c
          touch flag
      - name: increment version
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
      - name: set up git
        run: |
          gpg --import "${{ secrets.SUPERKEY }}"
          git config --global user.signingkey 6372B76B1D9482B2
          git config --global commit.gpgsign true
          git config --local user.email "joshua@joseos.com"
          git config --local user.name "joshybot 🤖"
      - name: Commit
        run: |
          git add .
          git commit -m "🤖"
          git push origin "$TAG"
          git push origin main
