name: Build

on:
  push:
    paths:
      - "linux.bash"
      - "server.bash"
      - "mac.bash"
      - "!sh"
      - "!mac"
  workflow_dispatch:

jobs:
  buildl:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: install shc
        run: |
          sudo apt install -y shc
      - name: Pre-Cleanup
        run: |
          rm sh
          rm server
      - name: Build
        run: |
          shc -rvf linux.bash -o sh
          shc -rvf server.bash -o server
      - name: Post-Cleanup
        run: |
          rm linux.bash.x.c
          rm server.bash.x.c
      - name: set up git
        run: |
          git config --local user.email "joshua@joseos.com"
          git config --local user.name "joshy[bot]"
      - name: Commit
        run: |
          git add .
          git commit -m "🤖"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  buildm:
    needs: buildl
    name: Build for MacOS
    runs-on: macos-latest
    steps:
      - name: install shc
        run: |
          brew install shc
      - name: sleep
        run: |
          sleep 5
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          token: ${{ secrets.PAT }}
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: sleep
        run: |
          sleep 5
      - name: Pre-Cleanup
        run: |
          rm mac
      - name: Build
        run: |
          shc -rvf mac.bash -o mac
      - name: Post-Cleanup
        run: |
          rm mac.bash.x.c
      - name: set up git
        run: |
          git config --local user.email "joshua@joseos.com"
          git config --local user.name "joshy[bot]"
      - name: Commit
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          TAGY="${TAG:5:2}"
          TAGX=$(($TAGY+1))
          TAGA="${TAG:0:5}"
          TAGF="$TAGA$TAGX"
          printf "TAGF"
          git add .
          git commit -m "🤖"
          git tag "$TAGF"
      - name: Push changes to release
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: $TAGF
      - name: Push to main
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: main

  release:
    needs: [buildl, buildm]
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mac
            sh
            server
