name: 🛠

on:
  push:
    branches:
      - main
    paths:
      - "**.bash"
  workflow_dispatch:

jobs:
  buildl:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
      - name: install shc
        run: |
          sudo apt install -y shc
      - name: Pre-Cleanup
        run: |
          rm ./dist/server
          rm ./dist/sh
          rm ./dist/mac
      - name: Build
        run: |
          shc -rvf scripts/linux.bash -o ./dist/sh
          chmod +x ./dist/sh
          rm scripts/linux.bash.x.c
          shc -rvf scripts/server.bash -o ./dist/server
          rm scripts/server.bash.x.c
          chmod +x ./dist/server
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_push_gpgsign: false
      - name: set up git
        run: |
          git config --global gpg.program gpg2
      - name: Commit
        run: |
          git add ./dist/sh ./dist/server
          git commit -m "✨"
      - name: Push changes
        uses: ad-m/github-push-action@master
  buildm:
    needs: buildl
    name: Build for MacOS
    runs-on: macos-latest
    steps:
      - name: install shc
        run: |
          brew install shc
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PATN }}
          fetch-depth: 0
          ref: main
      - name: Build
        run: |
          shc -rvf scripts/mac.bash -o ./dist/mac
          rm scripts/mac.bash.x.c
          chmod +x ./dist/mac
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPGN }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_push_gpgsign: false
      - name: increment + commit
        env:
          key: ${{ secrets.SENTRYKEY }}
        run: dist/increment
