name: Build

on:
  push:
    branches:
      - main
    paths:
      - "**.bash"
  workflow_dispatch:

jobs:
  buildl:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          token: ${{ secrets.PAT }}
      - name: install shc
        run: |
          sudo apt install -y shc
      - name: Pre-Cleanup
        run: |
          rm sh
          rm server
      - name: Build
        run: |
          shc -rvf linux.bash -o sh
          shc -rvf server.bash -o server
      - name: Post-Cleanup
        run: |
          rm linux.bash.x.c
          rm server.bash.x.c
      - name: set up git
        run: |
          echo -n "${{ secrets.SUPERKEY }}" | base64 --decode -o private.key
          gpg --allow-secret-key-import private.key
          git config --global user.signingkey 6372B76B1D9482B2
          git config --global commit.gpgsign true
          git config --local user.email "joshua@joseos.com"
          git config --local user.name "joshy 🤖"
          rm private.key
      - name: Commit
        run: |
          git add .
          git commit -m "🤖✨"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
  buildm:
    needs: buildl
    name: Build for MacOS
    runs-on: macos-latest
    steps:
      - name: install shc
        run: |
          brew install shc
      - name: sleep
        run: |
          sleep 5
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
          ref: main
      - name: sleep
        run: |
          sleep 5
      - name: Pre-Cleanup
        run: |
          rm mac
      - name: Build
        run: |
          shc -rvf mac.bash -o mac
      - name: Post-Cleanup
        run: |
          rm mac.bash.x.c
      - name: set up git
        run: |
          echo -n "${{ secrets.SUPERKEY }}" | base64 --decode -o private.key
          gpg --allow-secret-key-import private.key
          git config --global user.signingkey 6372B76B1D9482B2
          git config --global commit.gpgsign true
          git config --local user.email "joshua@joseos.com"
          git config --local user.name "joshy 🤖"
      - name: Commit
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          TAGY="${TAG:5:2}"
          TAGX=$(($TAGY+1))
          TAGA="${TAG:0:5}"
          TAGL="${TAG:3:1}"
          TAGO="${TAG:1:1}"
          TAGF="$TAGA$TAGX"
          if [ "$TAGY" = 9 ];then;TAGX="0";if [ "$TAGL" = 9 ];then;TAGL=0;TAGO=$(($TAGO+1));else;TAGL=$(($TAGL+1));fi;TAGF="v$TAGO.$TAGL.$TAGX";fi
          printf "\n\n\n$TAGF\n\n\n\n"
          rm private.key
          git add .
          git commit -m "🤖⚡️"
          git tag "$TAGF"
          git push origin "$TAGF"
      - name: sleep
        run: |
          sleep 5
      - name: Push to main
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: main

  release:
    needs: [buildl, buildm]
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
          ref: main
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mac
            sh
            server
