name: 😮‍💨

on:
  push:
    branches:
      - main
    paths:
      - "**.go"
  workflow_dispatch:

jobs:
  buildl:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
      - name: Pre-Cleanup
        run: |
          rm ./dist/flexgit
          rm ./dist/increment
      - name: Build
        run: |
          go build -o ./dist/flexgit scripts/flexgit.go
          chmod +x ./dist/flexgit
          go get -d ./scripts/increment/...
          go build -o ./dist/increment scripts/increment/increment.go
          chmod +x ./dist/increment
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_push_gpgsign: false
      - name: set up git
        run: |
          git config --global gpg.program gpg2
      - name: increment + commit
        run: dist/increment
