name: Build

on:
  push:
    paths:
      - "mac.bash"
      - "!server.bash"
      - "!linux.bash"
      - "!sh"
      - "!mac"
  workflow_dispatch:

jobs:
  build for linux:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install shc
        run: |
          brew install shc
      - name: Pre-Cleanup
        run: |
          rm mac
      - name: Build
        run: |
          shc -rvf mac.bash -o mac
      - name: Post-Cleanup
        run: |
          rm mac.bash.x.c
      - name: increment version
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          TAGY="${TAG:5:2}
          TAGX=$(($TAGY+1))
          TAGA="${TAG:0:5}"
          TAGF="$TAGA$TAGX"
      - name: set up git
          gpg --import "${{ secrets.SUPERKEY }}"
          git config --global user.signingkey 6372B76B1D9482B2
          git config --global commit.gpgsign true
          git config --local user.email "joshua@joseos.com"
          git config --local user.name "joshybot 🤖"
      - name: Commit
        run: |
          git add .
          git commit -m "🤖"
          git tag "$TAGF"
          git push origin main
          git push origin "$TAGF"
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/joshhhhyyyy/5a303840db0ab88febbb95d360a45d48
          gist_title: mac.bash
          gist_description: [MacOS] system install + setup script
          github_file: mac.bash
