name: Build

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - uses: actions/checkout@v2
      - name: install shc
        run: |
          sudo apt install -y shc
      - name: Pre-Cleanup
        run: |
          rm sh
      - name: Build
        run: |
          shc -rvf bruh.bash -o sh
      - name: Post-Cleanup
        run: |
          rm bruh.bash.x.c
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: sh
      - name: Commit
        run: |
          git add .
          git config --local user.email "joshua@joseos.com"
          git config --local user.name "joshybot🤖"
          git commit -m "🤖" -a | exit 0
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Sync to gist
        uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/joshhhhyyyy/92ba395fd9caf8ef75c69951f916874a
          gist_title: bruh.bash
          gist_description: shell script to make my life easier
          github_file: bruh.bash
